### ISSUE TITLE
Invisible text on full comment page

### ISSUE THREAD

**Issue by jussiarpalahti** [City-of-Helsinki/devheldev#62]
Fix this: http://dev.hel.fi/commit-watch/

**Comment by juyrjola** [comment]
CSS marks the commit list white:
```css
.commit-list__item a {
    display: block;
    width: 85%;
    margin-left: 18%;
    margin-bottom: 0.75em;
    color: #FFFFFF;
}
```
